name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - feature/*

#defaults:
#  run:
#    working-directory: ./src/client

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Install dependencies
        run: |
          ls -la
          cd ./src/client
          npm ci --ignore-scripts
      - name: Check and run build
        run: |
          cd ./src/client
          npm run build
          ls -la

#      - name: Unit Test
#        run: npm run test

#  cypress-run:
#    runs-on: ubuntu-20.04
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#        
#      - name: Install dependencies
#        run: npm install
#
#      - name: Cypress run
#        uses: cypress-io/github-action@v2
#        with:
#          working-directory: ./src/client/
#          install-command: echo
#          build: npm run build
#          start: npx vite --port 3000
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@main

      - name: Authenticate using a Service Principal
        uses: azure/actions/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Build and push image'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push the image tagged with the git commit hash
        run: |
          docker build . -t zohotimesheetaw/demo:${{ github.sha }}
          ls -la
          rm -rf prod
          mkdir prod
          ls -la /prod