name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

defaults:
  run:
    working-directory: ./src/client

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Install dependencies
        run: npm ci --ignore-scripts
  
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Unit Test
        run: npm run test

#  cypress-run:
#    runs-on: ubuntu-20.04
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#        
#      - name: Install dependencies
#        run: npm install
#
#      - name: Cypress run
#        uses: cypress-io/github-action@v2
#        with:
#          working-directory: ./src/client/
#          install-command: echo
#          build: npm run build
#          start: npx vite --port 3000
